export const SignupApi="http://localhost:5000/adduser"
export const LoginApi="http://localhost:5000/userlogin"
export const BlogAddApi="http://localhost:5000/addblog"
export const GetAllBlog="http://localhost:5000/getallblog"
export const AuthorAddedblogs="http://localhost:5000/SingleAuthorAddedBlog/"