const baseUrl="https://blog-application-cglh.onrender.com/"


export const SignupApi=baseUrl+"adduser"
export const LoginApi=baseUrl+"userlogin"
export const BlogAddApi=baseUrl+"addblog"
export const GetAllBlog=baseUrl+"getallblog"
export const AuthorAddedblogs=baseUrl+"SingleAuthorAddedBlog/"
export const DeleteSingleBlog=baseUrl+"delete/"
export const EditoneBlog=baseUrl+"edit/"
export const CatagoryApi=baseUrl+"catagory/"
export const addComment=baseUrl+"addcomment"
export const getCommentsApi=baseUrl+"getcomments/"
export const BlogsOfSingleAuthorApi=baseUrl+"authorfullblog/"
export const addLikeApi=baseUrl+"likes"
export const likeCountApi=baseUrl+"getlike/"